accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from accounts.views import signup


urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", signup, name="signup"),
]

projects/urls.py
from django.urls import path
from projects.views import ProjectListView, ProjectDetailView

urlpatterns = [
    path("", ProjectListView.as_view(), name="list_projects"),
    path("<int:pk>/", ProjectDetailView.as_view(), name="show_project"),
]

tracker/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView


from projects.views import ProjectListView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("projects/", include("projects.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("list_projects")),
        name="home",
    ),
    path("accounts/", include("accounts.urls")),
]

accounts/models.py
from django.db import models

# Create your models here.

projects/models.py
from django.db import models
from django.conf import settings

# Create your models here.


class Project(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(null=True)
    members = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name="projects",
    )

    def __str__(self):
        return self.name

tasks/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Task(models.Model):
    name = models.CharField(max_length=200)
    start_date = models.DateTimeField()
    due_date = models.DateTimeField()
    is_completed = models.BooleanField(default=False)
    project = models.ForeignKey(
        "projects.Project", related_name="tasks", on_delete=models.CASCADE
    )
    assignee = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        related_name="tasks",
        on_delete=models.SET_NULL,
    )

    def __str__(self):
        return self.name

accounts/views.py
from django.contrib.auth import login
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect

# Create your views here.
def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = request.POST.get("username")
            password = request.POST.get("password1")
            user = User.objects.create_user(
                username=username,
                password=password,
            )
            user.save()
            login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm()
    context = {
        "form": form,
    }
    return render(request, "registration/signup.html", context)

projects/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from projects.models import Project
from django.contrib.auth.mixins import LoginRequiredMixin


# Create your views here.
class ProjectListView(LoginRequiredMixin, ListView):
    model = Project
    template_name = "projects/list.html"

    def get_queryset(self):
        return Project.objects.filter(members=self.request.user)


class ProjectDetailView(LoginRequiredMixin, DetailView):
    model = Project
    template_name = "projects/detail.html"

tasks/views.py
from django.shortcuts import render

# Create your views here.

projects/templates/projects/detail.html
{% load static %}
<!doctype html>
<html>

<head>
    <title></title>
</head>

<body>
    <main>
        <div>
            <!-- {% block content %} -->
            <h1>{{project.name}}</h1>
            <p>{{project.description}}</p>
            <h2>Task</h2>

            {% if project.tasks.all %}
            <table>
                <tr>
                    <th>Name</th>
                    <th>Assignee</th>
                    <th>Start date</th>
                    <th>Due date</th>
                    <th>Is completed</th>
                </tr>
                <!-- <tbody> -->
                {% for task in project.tasks.all %}
                <tr>
                    <td>{{task.name}}</td>
                    <td>{{task.assignee}}</td>
                    <td>{{task.start_date}}</td>
                    <td>{{task.due_date}}</td>
                    <td>{{task.is_completed}}</td>
                </tr>
                {% endfor %}
                <!-- </tbody>    -->
            </table>
            {% else %}
            <p>This project has no tasks</p>
            {% endif %}

            <!-- {% endblock content%} -->
        </div>
    </main>

</body>

</html>

projects/templates/projects/list.html
{% load static %}
<!doctype html>
<html>

<head>
    <title></title>
</head>

<body>
    <main>
        <div>
            <h1>My Projects</h1>

            {% if project_list %}
            <table>
                <tr>
                    <th>Name</th>
                    <th>Number of tasks</th>
                </tr>
                {% for project in project_list %}
                <tr>
                    <td><a href="{% url 'show_project' project.pk %}"> {{project.name}}</a> </td>
                    <td>{{ project.tasks.all | length}}</td>
                </tr>
                {% endfor %}
            </table>

            {% else %}
            <p>You are not assigned to any projects</p>


            {% endif %}


        </div>

    </main>

</body>

</html>